Don't install typing on Python 3.5+
Pypi's typing can cause errors like `AttributeError: type object
'Callable' has no attribute '_abc_registry'`.

Signed-off-by: Yves Bastide <yves@botify.com>