Fix command-line --local mode requiring SWF access
The local executor actually doesn't exit, so the rest of the code is
executed and raises immediately in local mode. With the README example:

    % simpleflow start --local examples.basic.BasicWorkflow <<< '{"args": [1]}'
    (1 + 1) * 2 = 4
    Traceback (most recent call last):
      File "/Users/jbbarth/.virtualenvs/simpleflow/bin/simpleflow", line 9, in <module>
        load_entry_point('simpleflow==0.6.1', 'console_scripts', 'simpleflow')()
      File "/Users/jbbarth/.virtualenvs/simpleflow/lib/python2.7/site-packages/click-4.0-py2.7.egg/click/core.py", line 664, in __call__
      File "/Users/jbbarth/.virtualenvs/simpleflow/lib/python2.7/site-packages/click-4.0-py2.7.egg/click/core.py", line 644, in main
      File "/Users/jbbarth/.virtualenvs/simpleflow/lib/python2.7/site-packages/click-4.0-py2.7.egg/click/core.py", line 991, in invoke
      File "/Users/jbbarth/.virtualenvs/simpleflow/lib/python2.7/site-packages/click-4.0-py2.7.egg/click/core.py", line 837, in invoke
      File "/Users/jbbarth/.virtualenvs/simpleflow/lib/python2.7/site-packages/click-4.0-py2.7.egg/click/core.py", line 464, in invoke
      File "/Users/jbbarth/.virtualenvs/simpleflow/lib/python2.7/site-packages/simpleflow-0.6.1-py2.7.egg/simpleflow/command.py", line 80, in start
        raise ValueError('*domain* must be set when not running in local mode')
    ValueError: *domain* must be set when not running in local mode